name: flutter_mycard
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: DMSerifText
      fonts:
        - asset: fonts/DMSerifText-Regular.ttf

    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf


dependency_overrides:
  material_color_utilities: ^0.12.0
  leak_tracker: ^10.0.9
  vm_service: ^15.0.0
